export const mapErrorsLabel: Record<string, string> = {
  USER_NOT_FOUND: 'Usuário não encontrado',
  FAILED_TO_CREATE_USER: 'Falha ao criar usuário',
  FAILED_TO_CREATE_SESSION: 'Falha ao criar sessão',
  FAILED_TO_UPDATE_USER: 'Falha ao atualizar usuário',
  FAILED_TO_GET_SESSION: 'Falha ao obter sessão',
  INVALID_PASSWORD: 'Senha inválida',
  INVALID_EMAIL: 'E-mail inválido',
  INVALID_EMAIL_OR_PASSWORD: 'E-mail ou senha inválidos',
  INVALID_USER: 'Usuário inválido',
  SOCIAL_ACCOUNT_ALREADY_LINKED: 'Conta social já vinculada',
  PROVIDER_NOT_FOUND: 'Provedor não encontrado',
  INVALID_TOKEN: 'Token inválido',
  TOKEN_EXPIRED: 'Token expirado',
  ID_TOKEN_NOT_SUPPORTED: 'id_token não é suportado',
  FAILED_TO_GET_USER_INFO: 'Falha ao obter informações do usuário',
  USER_EMAIL_NOT_FOUND: 'E-mail do usuário não encontrado',
  EMAIL_NOT_VERIFIED: 'E-mail não verificado',
  PASSWORD_TOO_SHORT: 'Senha muito curta',
  PASSWORD_TOO_LONG: 'Senha muito longa',
  USER_ALREADY_EXISTS: 'Usuário já existe.',
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL: 'Usuário já existe. Use outro e-mail.',
  EMAIL_CAN_NOT_BE_UPDATED: 'O e-mail não pode ser atualizado',
  CHANGE_EMAIL_DISABLED: 'A alteração de e-mail está desativada',
  CREDENTIAL_ACCOUNT_NOT_FOUND: 'Conta com credenciais não encontrada',
  SESSION_EXPIRED: 'Sessão expirada. Faça login novamente para continuar.',
  FAILED_TO_UNLINK_LAST_ACCOUNT: 'Você não pode desvincular sua última conta',
  ACCOUNT_NOT_FOUND: 'Conta não encontrada',
  USER_ALREADY_HAS_PASSWORD:
    'O usuário já possui uma senha. Informe essa senha para excluir a conta.',
  CROSS_SITE_NAVIGATION_LOGIN_BLOCKED:
    'Login por navegação entre sites bloqueado. Esta solicitação parece ser um ataque CSRF.',
  VERIFICATION_EMAIL_NOT_ENABLED: 'O e-mail de verificação não está habilitado',
  EMAIL_ALREADY_VERIFIED: 'O e-mail já foi verificado',
  EMAIL_MISMATCH: 'O e-mail não corresponde',
  SESSION_NOT_FRESH: 'A sessão não é recente',
  LINKED_ACCOUNT_ALREADY_EXISTS: 'Conta vinculada já existe',
  INVALID_ORIGIN: 'Origem inválida',
  INVALID_CALLBACK_URL: 'callbackURL inválida',
  INVALID_REDIRECT_URL: 'redirectURL inválida',
  INVALID_ERROR_CALLBACK_URL: 'errorCallbackURL inválida',
  INVALID_NEW_USER_CALLBACK_URL: 'newUserCallbackURL inválida',
  MISSING_OR_NULL_ORIGIN: 'Origem ausente ou nula',
  CALLBACK_URL_REQUIRED: 'callbackURL é obrigatória',
  FAILED_TO_CREATE_VERIFICATION: 'Não foi possível criar a verificação',
  FIELD_NOT_ALLOWED: 'Campo não permitido',
  ASYNC_VALIDATION_NOT_SUPPORTED: 'Validação assíncrona não é suportada',
  VALIDATION_ERROR: 'Erro de validação',
  MISSING_FIELD: 'Campo obrigatório',
  METHOD_NOT_ALLOWED_DEFER_SESSION_REQUIRED:
    'O método POST exige que deferSessionRefresh esteja habilitado na configuração de sessão',
  BODY_MUST_BE_AN_OBJECT: 'O corpo da requisição deve ser um objeto',
  PASSWORD_ALREADY_SET: 'O usuário já possui uma senha definida',
} as const
