/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthenticatedLayoutRouteImport } from './pages/_authenticated/layout'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'
import { Route as DashboardEstablishmentIdLayoutRouteImport } from './pages/dashboard/$establishmentId/layout'
import { Route as AuthenticatedOwnerLayoutRouteImport } from './pages/_authenticated/owner/layout'
import { Route as AuthenticatedProfileIndexRouteImport } from './pages/_authenticated/profile/index'
import { Route as AuthenticatedEstablishmentIndexRouteImport } from './pages/_authenticated/establishment/index'
import { Route as AuthRegisterIndexRouteImport } from './pages/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './pages/_auth/login/index'
import { Route as DashboardEstablishmentIdServicesIndexRouteImport } from './pages/dashboard/$establishmentId/services/index'
import { Route as DashboardEstablishmentIdReviewsIndexRouteImport } from './pages/dashboard/$establishmentId/reviews/index'
import { Route as DashboardEstablishmentIdOverviewIndexRouteImport } from './pages/dashboard/$establishmentId/overview/index'
import { Route as DashboardEstablishmentIdCustomersIndexRouteImport } from './pages/dashboard/$establishmentId/customers/index'
import { Route as DashboardEstablishmentIdCollaboratorsIndexRouteImport } from './pages/dashboard/$establishmentId/collaborators/index'
import { Route as DashboardEstablishmentIdAppointmentsIndexRouteImport } from './pages/dashboard/$establishmentId/appointments/index'
import { Route as AuthenticatedOwnerRoutesNewIndexRouteImport } from './pages/_authenticated/owner/_routes/new/index'
import { Route as AuthenticatedOwnerRoutesOwnerIdIndexRouteImport } from './pages/_authenticated/owner/_routes/$ownerId/index'
import { Route as AuthenticatedEstablishmentRoutesNewIndexRouteImport } from './pages/_authenticated/establishment/_routes/new/index'
import { Route as AuthenticatedEstablishmentRoutesEstablishmentIdIndexRouteImport } from './pages/_authenticated/establishment/_routes/$establishmentId/index'
import { Route as DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteImport } from './pages/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/layout'
import { Route as DashboardEstablishmentIdServicesPagesNewIndexRouteImport } from './pages/dashboard/$establishmentId/services/_pages/new/index'
import { Route as DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRouteImport } from './pages/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/info/index'
import { Route as DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRouteImport } from './pages/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/edit/index'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEstablishmentIdLayoutRoute =
  DashboardEstablishmentIdLayoutRouteImport.update({
    id: '/dashboard/$establishmentId',
    path: '/dashboard/$establishmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOwnerLayoutRoute =
  AuthenticatedOwnerLayoutRouteImport.update({
    id: '/owner',
    path: '/owner',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedEstablishmentIndexRoute =
  AuthenticatedEstablishmentIndexRouteImport.update({
    id: '/establishment/',
    path: '/establishment/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardEstablishmentIdServicesIndexRoute =
  DashboardEstablishmentIdServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const DashboardEstablishmentIdReviewsIndexRoute =
  DashboardEstablishmentIdReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const DashboardEstablishmentIdOverviewIndexRoute =
  DashboardEstablishmentIdOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const DashboardEstablishmentIdCustomersIndexRoute =
  DashboardEstablishmentIdCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const DashboardEstablishmentIdCollaboratorsIndexRoute =
  DashboardEstablishmentIdCollaboratorsIndexRouteImport.update({
    id: '/collaborators/',
    path: '/collaborators/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const DashboardEstablishmentIdAppointmentsIndexRoute =
  DashboardEstablishmentIdAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const AuthenticatedOwnerRoutesNewIndexRoute =
  AuthenticatedOwnerRoutesNewIndexRouteImport.update({
    id: '/_routes/new/',
    path: '/new/',
    getParentRoute: () => AuthenticatedOwnerLayoutRoute,
  } as any)
const AuthenticatedOwnerRoutesOwnerIdIndexRoute =
  AuthenticatedOwnerRoutesOwnerIdIndexRouteImport.update({
    id: '/_routes/$ownerId/',
    path: '/$ownerId/',
    getParentRoute: () => AuthenticatedOwnerLayoutRoute,
  } as any)
const AuthenticatedEstablishmentRoutesNewIndexRoute =
  AuthenticatedEstablishmentRoutesNewIndexRouteImport.update({
    id: '/establishment/_routes/new/',
    path: '/establishment/new/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute =
  AuthenticatedEstablishmentRoutesEstablishmentIdIndexRouteImport.update({
    id: '/establishment/_routes/$establishmentId/',
    path: '/establishment/$establishmentId/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute =
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteImport.update(
    {
      id: '/services/_pages/$serviceEstablishmentId',
      path: '/services/$serviceEstablishmentId',
      getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
    } as any,
  )
const DashboardEstablishmentIdServicesPagesNewIndexRoute =
  DashboardEstablishmentIdServicesPagesNewIndexRouteImport.update({
    id: '/services/_pages/new/',
    path: '/services/new/',
    getParentRoute: () => DashboardEstablishmentIdLayoutRoute,
  } as any)
const DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute =
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRouteImport.update(
    {
      id: '/info/',
      path: '/info/',
      getParentRoute: () =>
        DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute,
    } as any,
  )
const DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute =
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRouteImport.update(
    {
      id: '/edit/',
      path: '/edit/',
      getParentRoute: () =>
        DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof AuthenticatedOwnerLayoutRouteWithChildren
  '/dashboard/$establishmentId': typeof DashboardEstablishmentIdLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/establishment/': typeof AuthenticatedEstablishmentIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/dashboard/$establishmentId/appointments/': typeof DashboardEstablishmentIdAppointmentsIndexRoute
  '/dashboard/$establishmentId/collaborators/': typeof DashboardEstablishmentIdCollaboratorsIndexRoute
  '/dashboard/$establishmentId/customers/': typeof DashboardEstablishmentIdCustomersIndexRoute
  '/dashboard/$establishmentId/overview/': typeof DashboardEstablishmentIdOverviewIndexRoute
  '/dashboard/$establishmentId/reviews/': typeof DashboardEstablishmentIdReviewsIndexRoute
  '/dashboard/$establishmentId/services/': typeof DashboardEstablishmentIdServicesIndexRoute
  '/dashboard/$establishmentId/services/$serviceEstablishmentId': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  '/establishment/$establishmentId/': typeof AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute
  '/establishment/new/': typeof AuthenticatedEstablishmentRoutesNewIndexRoute
  '/owner/$ownerId/': typeof AuthenticatedOwnerRoutesOwnerIdIndexRoute
  '/owner/new/': typeof AuthenticatedOwnerRoutesNewIndexRoute
  '/dashboard/$establishmentId/services/new/': typeof DashboardEstablishmentIdServicesPagesNewIndexRoute
  '/dashboard/$establishmentId/services/$serviceEstablishmentId/edit/': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute
  '/dashboard/$establishmentId/services/$serviceEstablishmentId/info/': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof AuthenticatedOwnerLayoutRouteWithChildren
  '/dashboard/$establishmentId': typeof DashboardEstablishmentIdLayoutRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/establishment': typeof AuthenticatedEstablishmentIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/dashboard/$establishmentId/appointments': typeof DashboardEstablishmentIdAppointmentsIndexRoute
  '/dashboard/$establishmentId/collaborators': typeof DashboardEstablishmentIdCollaboratorsIndexRoute
  '/dashboard/$establishmentId/customers': typeof DashboardEstablishmentIdCustomersIndexRoute
  '/dashboard/$establishmentId/overview': typeof DashboardEstablishmentIdOverviewIndexRoute
  '/dashboard/$establishmentId/reviews': typeof DashboardEstablishmentIdReviewsIndexRoute
  '/dashboard/$establishmentId/services': typeof DashboardEstablishmentIdServicesIndexRoute
  '/dashboard/$establishmentId/services/$serviceEstablishmentId': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  '/establishment/$establishmentId': typeof AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute
  '/establishment/new': typeof AuthenticatedEstablishmentRoutesNewIndexRoute
  '/owner/$ownerId': typeof AuthenticatedOwnerRoutesOwnerIdIndexRoute
  '/owner/new': typeof AuthenticatedOwnerRoutesNewIndexRoute
  '/dashboard/$establishmentId/services/new': typeof DashboardEstablishmentIdServicesPagesNewIndexRoute
  '/dashboard/$establishmentId/services/$serviceEstablishmentId/edit': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute
  '/dashboard/$establishmentId/services/$serviceEstablishmentId/info': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerLayoutRouteWithChildren
  '/dashboard/$establishmentId': typeof DashboardEstablishmentIdLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/establishment/': typeof AuthenticatedEstablishmentIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/dashboard/$establishmentId/appointments/': typeof DashboardEstablishmentIdAppointmentsIndexRoute
  '/dashboard/$establishmentId/collaborators/': typeof DashboardEstablishmentIdCollaboratorsIndexRoute
  '/dashboard/$establishmentId/customers/': typeof DashboardEstablishmentIdCustomersIndexRoute
  '/dashboard/$establishmentId/overview/': typeof DashboardEstablishmentIdOverviewIndexRoute
  '/dashboard/$establishmentId/reviews/': typeof DashboardEstablishmentIdReviewsIndexRoute
  '/dashboard/$establishmentId/services/': typeof DashboardEstablishmentIdServicesIndexRoute
  '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  '/_authenticated/establishment/_routes/$establishmentId/': typeof AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute
  '/_authenticated/establishment/_routes/new/': typeof AuthenticatedEstablishmentRoutesNewIndexRoute
  '/_authenticated/owner/_routes/$ownerId/': typeof AuthenticatedOwnerRoutesOwnerIdIndexRoute
  '/_authenticated/owner/_routes/new/': typeof AuthenticatedOwnerRoutesNewIndexRoute
  '/dashboard/$establishmentId/services/_pages/new/': typeof DashboardEstablishmentIdServicesPagesNewIndexRoute
  '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/edit/': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute
  '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/info/': typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/dashboard/$establishmentId'
    | '/dashboard/'
    | '/login/'
    | '/register/'
    | '/establishment/'
    | '/profile/'
    | '/dashboard/$establishmentId/appointments/'
    | '/dashboard/$establishmentId/collaborators/'
    | '/dashboard/$establishmentId/customers/'
    | '/dashboard/$establishmentId/overview/'
    | '/dashboard/$establishmentId/reviews/'
    | '/dashboard/$establishmentId/services/'
    | '/dashboard/$establishmentId/services/$serviceEstablishmentId'
    | '/establishment/$establishmentId/'
    | '/establishment/new/'
    | '/owner/$ownerId/'
    | '/owner/new/'
    | '/dashboard/$establishmentId/services/new/'
    | '/dashboard/$establishmentId/services/$serviceEstablishmentId/edit/'
    | '/dashboard/$establishmentId/services/$serviceEstablishmentId/info/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner'
    | '/dashboard/$establishmentId'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/establishment'
    | '/profile'
    | '/dashboard/$establishmentId/appointments'
    | '/dashboard/$establishmentId/collaborators'
    | '/dashboard/$establishmentId/customers'
    | '/dashboard/$establishmentId/overview'
    | '/dashboard/$establishmentId/reviews'
    | '/dashboard/$establishmentId/services'
    | '/dashboard/$establishmentId/services/$serviceEstablishmentId'
    | '/establishment/$establishmentId'
    | '/establishment/new'
    | '/owner/$ownerId'
    | '/owner/new'
    | '/dashboard/$establishmentId/services/new'
    | '/dashboard/$establishmentId/services/$serviceEstablishmentId/edit'
    | '/dashboard/$establishmentId/services/$serviceEstablishmentId/info'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/owner'
    | '/dashboard/$establishmentId'
    | '/dashboard/'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authenticated/establishment/'
    | '/_authenticated/profile/'
    | '/dashboard/$establishmentId/appointments/'
    | '/dashboard/$establishmentId/collaborators/'
    | '/dashboard/$establishmentId/customers/'
    | '/dashboard/$establishmentId/overview/'
    | '/dashboard/$establishmentId/reviews/'
    | '/dashboard/$establishmentId/services/'
    | '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId'
    | '/_authenticated/establishment/_routes/$establishmentId/'
    | '/_authenticated/establishment/_routes/new/'
    | '/_authenticated/owner/_routes/$ownerId/'
    | '/_authenticated/owner/_routes/new/'
    | '/dashboard/$establishmentId/services/_pages/new/'
    | '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/edit/'
    | '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/info/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  DashboardEstablishmentIdLayoutRoute: typeof DashboardEstablishmentIdLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$establishmentId': {
      id: '/dashboard/$establishmentId'
      path: '/dashboard/$establishmentId'
      fullPath: '/dashboard/$establishmentId'
      preLoaderRoute: typeof DashboardEstablishmentIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/establishment/': {
      id: '/_authenticated/establishment/'
      path: '/establishment'
      fullPath: '/establishment/'
      preLoaderRoute: typeof AuthenticatedEstablishmentIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/$establishmentId/services/': {
      id: '/dashboard/$establishmentId/services/'
      path: '/services'
      fullPath: '/dashboard/$establishmentId/services/'
      preLoaderRoute: typeof DashboardEstablishmentIdServicesIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/reviews/': {
      id: '/dashboard/$establishmentId/reviews/'
      path: '/reviews'
      fullPath: '/dashboard/$establishmentId/reviews/'
      preLoaderRoute: typeof DashboardEstablishmentIdReviewsIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/overview/': {
      id: '/dashboard/$establishmentId/overview/'
      path: '/overview'
      fullPath: '/dashboard/$establishmentId/overview/'
      preLoaderRoute: typeof DashboardEstablishmentIdOverviewIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/customers/': {
      id: '/dashboard/$establishmentId/customers/'
      path: '/customers'
      fullPath: '/dashboard/$establishmentId/customers/'
      preLoaderRoute: typeof DashboardEstablishmentIdCustomersIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/collaborators/': {
      id: '/dashboard/$establishmentId/collaborators/'
      path: '/collaborators'
      fullPath: '/dashboard/$establishmentId/collaborators/'
      preLoaderRoute: typeof DashboardEstablishmentIdCollaboratorsIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/appointments/': {
      id: '/dashboard/$establishmentId/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/$establishmentId/appointments/'
      preLoaderRoute: typeof DashboardEstablishmentIdAppointmentsIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/_authenticated/owner/_routes/new/': {
      id: '/_authenticated/owner/_routes/new/'
      path: '/new'
      fullPath: '/owner/new/'
      preLoaderRoute: typeof AuthenticatedOwnerRoutesNewIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerLayoutRoute
    }
    '/_authenticated/owner/_routes/$ownerId/': {
      id: '/_authenticated/owner/_routes/$ownerId/'
      path: '/$ownerId'
      fullPath: '/owner/$ownerId/'
      preLoaderRoute: typeof AuthenticatedOwnerRoutesOwnerIdIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerLayoutRoute
    }
    '/_authenticated/establishment/_routes/new/': {
      id: '/_authenticated/establishment/_routes/new/'
      path: '/establishment/new'
      fullPath: '/establishment/new/'
      preLoaderRoute: typeof AuthenticatedEstablishmentRoutesNewIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/establishment/_routes/$establishmentId/': {
      id: '/_authenticated/establishment/_routes/$establishmentId/'
      path: '/establishment/$establishmentId'
      fullPath: '/establishment/$establishmentId/'
      preLoaderRoute: typeof AuthenticatedEstablishmentRoutesEstablishmentIdIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId': {
      id: '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId'
      path: '/services/$serviceEstablishmentId'
      fullPath: '/dashboard/$establishmentId/services/$serviceEstablishmentId'
      preLoaderRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/services/_pages/new/': {
      id: '/dashboard/$establishmentId/services/_pages/new/'
      path: '/services/new'
      fullPath: '/dashboard/$establishmentId/services/new/'
      preLoaderRoute: typeof DashboardEstablishmentIdServicesPagesNewIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/info/': {
      id: '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/info/'
      path: '/info'
      fullPath: '/dashboard/$establishmentId/services/$serviceEstablishmentId/info/'
      preLoaderRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute
    }
    '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/edit/': {
      id: '/dashboard/$establishmentId/services/_pages/$serviceEstablishmentId/edit/'
      path: '/edit'
      fullPath: '/dashboard/$establishmentId/services/$serviceEstablishmentId/edit/'
      preLoaderRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRouteImport
      parentRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthenticatedOwnerLayoutRouteChildren {
  AuthenticatedOwnerRoutesOwnerIdIndexRoute: typeof AuthenticatedOwnerRoutesOwnerIdIndexRoute
  AuthenticatedOwnerRoutesNewIndexRoute: typeof AuthenticatedOwnerRoutesNewIndexRoute
}

const AuthenticatedOwnerLayoutRouteChildren: AuthenticatedOwnerLayoutRouteChildren =
  {
    AuthenticatedOwnerRoutesOwnerIdIndexRoute:
      AuthenticatedOwnerRoutesOwnerIdIndexRoute,
    AuthenticatedOwnerRoutesNewIndexRoute:
      AuthenticatedOwnerRoutesNewIndexRoute,
  }

const AuthenticatedOwnerLayoutRouteWithChildren =
  AuthenticatedOwnerLayoutRoute._addFileChildren(
    AuthenticatedOwnerLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedOwnerLayoutRoute: typeof AuthenticatedOwnerLayoutRouteWithChildren
  AuthenticatedEstablishmentIndexRoute: typeof AuthenticatedEstablishmentIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute: typeof AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute
  AuthenticatedEstablishmentRoutesNewIndexRoute: typeof AuthenticatedEstablishmentRoutesNewIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedOwnerLayoutRoute: AuthenticatedOwnerLayoutRouteWithChildren,
  AuthenticatedEstablishmentIndexRoute: AuthenticatedEstablishmentIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute:
    AuthenticatedEstablishmentRoutesEstablishmentIdIndexRoute,
  AuthenticatedEstablishmentRoutesNewIndexRoute:
    AuthenticatedEstablishmentRoutesNewIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteChildren {
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute
}

const DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteChildren: DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteChildren =
  {
    DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute:
      DashboardEstablishmentIdServicesPagesServiceEstablishmentIdEditIndexRoute,
    DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute:
      DashboardEstablishmentIdServicesPagesServiceEstablishmentIdInfoIndexRoute,
  }

const DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteWithChildren =
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute._addFileChildren(
    DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteChildren,
  )

interface DashboardEstablishmentIdLayoutRouteChildren {
  DashboardEstablishmentIdAppointmentsIndexRoute: typeof DashboardEstablishmentIdAppointmentsIndexRoute
  DashboardEstablishmentIdCollaboratorsIndexRoute: typeof DashboardEstablishmentIdCollaboratorsIndexRoute
  DashboardEstablishmentIdCustomersIndexRoute: typeof DashboardEstablishmentIdCustomersIndexRoute
  DashboardEstablishmentIdOverviewIndexRoute: typeof DashboardEstablishmentIdOverviewIndexRoute
  DashboardEstablishmentIdReviewsIndexRoute: typeof DashboardEstablishmentIdReviewsIndexRoute
  DashboardEstablishmentIdServicesIndexRoute: typeof DashboardEstablishmentIdServicesIndexRoute
  DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute: typeof DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  DashboardEstablishmentIdServicesPagesNewIndexRoute: typeof DashboardEstablishmentIdServicesPagesNewIndexRoute
}

const DashboardEstablishmentIdLayoutRouteChildren: DashboardEstablishmentIdLayoutRouteChildren =
  {
    DashboardEstablishmentIdAppointmentsIndexRoute:
      DashboardEstablishmentIdAppointmentsIndexRoute,
    DashboardEstablishmentIdCollaboratorsIndexRoute:
      DashboardEstablishmentIdCollaboratorsIndexRoute,
    DashboardEstablishmentIdCustomersIndexRoute:
      DashboardEstablishmentIdCustomersIndexRoute,
    DashboardEstablishmentIdOverviewIndexRoute:
      DashboardEstablishmentIdOverviewIndexRoute,
    DashboardEstablishmentIdReviewsIndexRoute:
      DashboardEstablishmentIdReviewsIndexRoute,
    DashboardEstablishmentIdServicesIndexRoute:
      DashboardEstablishmentIdServicesIndexRoute,
    DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRoute:
      DashboardEstablishmentIdServicesPagesServiceEstablishmentIdLayoutRouteWithChildren,
    DashboardEstablishmentIdServicesPagesNewIndexRoute:
      DashboardEstablishmentIdServicesPagesNewIndexRoute,
  }

const DashboardEstablishmentIdLayoutRouteWithChildren =
  DashboardEstablishmentIdLayoutRoute._addFileChildren(
    DashboardEstablishmentIdLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  DashboardEstablishmentIdLayoutRoute:
    DashboardEstablishmentIdLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
