/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ErrorRouteImport } from './pages/error'
import { Route as AuthenticatedLayoutRouteImport } from './pages/_authenticated/layout'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'
import { Route as DashboardSlugLayoutRouteImport } from './pages/dashboard/$slug/layout'
import { Route as AuthenticatedProfileIndexRouteImport } from './pages/_authenticated/profile/index'
import { Route as AuthenticatedOwnerIndexRouteImport } from './pages/_authenticated/owner/index'
import { Route as AuthenticatedEstablishmentIndexRouteImport } from './pages/_authenticated/establishment/index'
import { Route as AuthRegisterIndexRouteImport } from './pages/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './pages/_auth/login/index'
import { Route as DashboardSlugServicesIndexRouteImport } from './pages/dashboard/$slug/services/index'
import { Route as DashboardSlugReviewsIndexRouteImport } from './pages/dashboard/$slug/reviews/index'
import { Route as DashboardSlugOverviewIndexRouteImport } from './pages/dashboard/$slug/overview/index'
import { Route as DashboardSlugCustomersIndexRouteImport } from './pages/dashboard/$slug/customers/index'
import { Route as DashboardSlugCollaboratorsIndexRouteImport } from './pages/dashboard/$slug/collaborators/index'
import { Route as DashboardSlugBookingsIndexRouteImport } from './pages/dashboard/$slug/bookings/index'
import { Route as AuthenticatedEstablishmentRoutesNewIndexRouteImport } from './pages/_authenticated/establishment/_routes/new/index'
import { Route as AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRouteImport } from './pages/_authenticated/establishment/_routes/$establishmentSlug/index'
import { Route as DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteImport } from './pages/dashboard/$slug/services/_pages/$serviceEstablishmentId/layout'
import { Route as DashboardSlugServicesPagesNewIndexRouteImport } from './pages/dashboard/$slug/services/_pages/new/index'
import { Route as DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRouteImport } from './pages/dashboard/$slug/services/_pages/$serviceEstablishmentId/info/index'
import { Route as DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRouteImport } from './pages/dashboard/$slug/services/_pages/$serviceEstablishmentId/edit/index'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSlugLayoutRoute = DashboardSlugLayoutRouteImport.update({
  id: '/dashboard/$slug',
  path: '/dashboard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedEstablishmentIndexRoute =
  AuthenticatedEstablishmentIndexRouteImport.update({
    id: '/establishment/',
    path: '/establishment/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardSlugServicesIndexRoute =
  DashboardSlugServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugReviewsIndexRoute =
  DashboardSlugReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugOverviewIndexRoute =
  DashboardSlugOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugCustomersIndexRoute =
  DashboardSlugCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugCollaboratorsIndexRoute =
  DashboardSlugCollaboratorsIndexRouteImport.update({
    id: '/collaborators/',
    path: '/collaborators/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugBookingsIndexRoute =
  DashboardSlugBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const AuthenticatedEstablishmentRoutesNewIndexRoute =
  AuthenticatedEstablishmentRoutesNewIndexRouteImport.update({
    id: '/establishment/_routes/new/',
    path: '/establishment/new/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute =
  AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRouteImport.update({
    id: '/establishment/_routes/$establishmentSlug/',
    path: '/establishment/$establishmentSlug/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute =
  DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteImport.update({
    id: '/services/_pages/$serviceEstablishmentId',
    path: '/services/$serviceEstablishmentId',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugServicesPagesNewIndexRoute =
  DashboardSlugServicesPagesNewIndexRouteImport.update({
    id: '/services/_pages/new/',
    path: '/services/new/',
    getParentRoute: () => DashboardSlugLayoutRoute,
  } as any)
const DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute =
  DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRouteImport.update({
    id: '/info/',
    path: '/info/',
    getParentRoute: () =>
      DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute,
  } as any)
const DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute =
  DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () =>
      DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/dashboard/$slug': typeof DashboardSlugLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/establishment/': typeof AuthenticatedEstablishmentIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/dashboard/$slug/bookings/': typeof DashboardSlugBookingsIndexRoute
  '/dashboard/$slug/collaborators/': typeof DashboardSlugCollaboratorsIndexRoute
  '/dashboard/$slug/customers/': typeof DashboardSlugCustomersIndexRoute
  '/dashboard/$slug/overview/': typeof DashboardSlugOverviewIndexRoute
  '/dashboard/$slug/reviews/': typeof DashboardSlugReviewsIndexRoute
  '/dashboard/$slug/services/': typeof DashboardSlugServicesIndexRoute
  '/dashboard/$slug/services/$serviceEstablishmentId': typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  '/establishment/$establishmentSlug/': typeof AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute
  '/establishment/new/': typeof AuthenticatedEstablishmentRoutesNewIndexRoute
  '/dashboard/$slug/services/new/': typeof DashboardSlugServicesPagesNewIndexRoute
  '/dashboard/$slug/services/$serviceEstablishmentId/edit/': typeof DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute
  '/dashboard/$slug/services/$serviceEstablishmentId/info/': typeof DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/dashboard/$slug': typeof DashboardSlugLayoutRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/establishment': typeof AuthenticatedEstablishmentIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/dashboard/$slug/bookings': typeof DashboardSlugBookingsIndexRoute
  '/dashboard/$slug/collaborators': typeof DashboardSlugCollaboratorsIndexRoute
  '/dashboard/$slug/customers': typeof DashboardSlugCustomersIndexRoute
  '/dashboard/$slug/overview': typeof DashboardSlugOverviewIndexRoute
  '/dashboard/$slug/reviews': typeof DashboardSlugReviewsIndexRoute
  '/dashboard/$slug/services': typeof DashboardSlugServicesIndexRoute
  '/dashboard/$slug/services/$serviceEstablishmentId': typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  '/establishment/$establishmentSlug': typeof AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute
  '/establishment/new': typeof AuthenticatedEstablishmentRoutesNewIndexRoute
  '/dashboard/$slug/services/new': typeof DashboardSlugServicesPagesNewIndexRoute
  '/dashboard/$slug/services/$serviceEstablishmentId/edit': typeof DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute
  '/dashboard/$slug/services/$serviceEstablishmentId/info': typeof DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/error': typeof ErrorRoute
  '/dashboard/$slug': typeof DashboardSlugLayoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/establishment/': typeof AuthenticatedEstablishmentIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/dashboard/$slug/bookings/': typeof DashboardSlugBookingsIndexRoute
  '/dashboard/$slug/collaborators/': typeof DashboardSlugCollaboratorsIndexRoute
  '/dashboard/$slug/customers/': typeof DashboardSlugCustomersIndexRoute
  '/dashboard/$slug/overview/': typeof DashboardSlugOverviewIndexRoute
  '/dashboard/$slug/reviews/': typeof DashboardSlugReviewsIndexRoute
  '/dashboard/$slug/services/': typeof DashboardSlugServicesIndexRoute
  '/dashboard/$slug/services/_pages/$serviceEstablishmentId': typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  '/_authenticated/establishment/_routes/$establishmentSlug/': typeof AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute
  '/_authenticated/establishment/_routes/new/': typeof AuthenticatedEstablishmentRoutesNewIndexRoute
  '/dashboard/$slug/services/_pages/new/': typeof DashboardSlugServicesPagesNewIndexRoute
  '/dashboard/$slug/services/_pages/$serviceEstablishmentId/edit/': typeof DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute
  '/dashboard/$slug/services/_pages/$serviceEstablishmentId/info/': typeof DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/dashboard/$slug'
    | '/dashboard/'
    | '/login/'
    | '/register/'
    | '/establishment/'
    | '/owner/'
    | '/profile/'
    | '/dashboard/$slug/bookings/'
    | '/dashboard/$slug/collaborators/'
    | '/dashboard/$slug/customers/'
    | '/dashboard/$slug/overview/'
    | '/dashboard/$slug/reviews/'
    | '/dashboard/$slug/services/'
    | '/dashboard/$slug/services/$serviceEstablishmentId'
    | '/establishment/$establishmentSlug/'
    | '/establishment/new/'
    | '/dashboard/$slug/services/new/'
    | '/dashboard/$slug/services/$serviceEstablishmentId/edit/'
    | '/dashboard/$slug/services/$serviceEstablishmentId/info/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/dashboard/$slug'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/establishment'
    | '/owner'
    | '/profile'
    | '/dashboard/$slug/bookings'
    | '/dashboard/$slug/collaborators'
    | '/dashboard/$slug/customers'
    | '/dashboard/$slug/overview'
    | '/dashboard/$slug/reviews'
    | '/dashboard/$slug/services'
    | '/dashboard/$slug/services/$serviceEstablishmentId'
    | '/establishment/$establishmentSlug'
    | '/establishment/new'
    | '/dashboard/$slug/services/new'
    | '/dashboard/$slug/services/$serviceEstablishmentId/edit'
    | '/dashboard/$slug/services/$serviceEstablishmentId/info'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/error'
    | '/dashboard/$slug'
    | '/dashboard/'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authenticated/establishment/'
    | '/_authenticated/owner/'
    | '/_authenticated/profile/'
    | '/dashboard/$slug/bookings/'
    | '/dashboard/$slug/collaborators/'
    | '/dashboard/$slug/customers/'
    | '/dashboard/$slug/overview/'
    | '/dashboard/$slug/reviews/'
    | '/dashboard/$slug/services/'
    | '/dashboard/$slug/services/_pages/$serviceEstablishmentId'
    | '/_authenticated/establishment/_routes/$establishmentSlug/'
    | '/_authenticated/establishment/_routes/new/'
    | '/dashboard/$slug/services/_pages/new/'
    | '/dashboard/$slug/services/_pages/$serviceEstablishmentId/edit/'
    | '/dashboard/$slug/services/_pages/$serviceEstablishmentId/info/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  DashboardSlugLayoutRoute: typeof DashboardSlugLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$slug': {
      id: '/dashboard/$slug'
      path: '/dashboard/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof DashboardSlugLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/establishment/': {
      id: '/_authenticated/establishment/'
      path: '/establishment'
      fullPath: '/establishment/'
      preLoaderRoute: typeof AuthenticatedEstablishmentIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/$slug/services/': {
      id: '/dashboard/$slug/services/'
      path: '/services'
      fullPath: '/dashboard/$slug/services/'
      preLoaderRoute: typeof DashboardSlugServicesIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/reviews/': {
      id: '/dashboard/$slug/reviews/'
      path: '/reviews'
      fullPath: '/dashboard/$slug/reviews/'
      preLoaderRoute: typeof DashboardSlugReviewsIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/overview/': {
      id: '/dashboard/$slug/overview/'
      path: '/overview'
      fullPath: '/dashboard/$slug/overview/'
      preLoaderRoute: typeof DashboardSlugOverviewIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/customers/': {
      id: '/dashboard/$slug/customers/'
      path: '/customers'
      fullPath: '/dashboard/$slug/customers/'
      preLoaderRoute: typeof DashboardSlugCustomersIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/collaborators/': {
      id: '/dashboard/$slug/collaborators/'
      path: '/collaborators'
      fullPath: '/dashboard/$slug/collaborators/'
      preLoaderRoute: typeof DashboardSlugCollaboratorsIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/bookings/': {
      id: '/dashboard/$slug/bookings/'
      path: '/bookings'
      fullPath: '/dashboard/$slug/bookings/'
      preLoaderRoute: typeof DashboardSlugBookingsIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/_authenticated/establishment/_routes/new/': {
      id: '/_authenticated/establishment/_routes/new/'
      path: '/establishment/new'
      fullPath: '/establishment/new/'
      preLoaderRoute: typeof AuthenticatedEstablishmentRoutesNewIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/establishment/_routes/$establishmentSlug/': {
      id: '/_authenticated/establishment/_routes/$establishmentSlug/'
      path: '/establishment/$establishmentSlug'
      fullPath: '/establishment/$establishmentSlug/'
      preLoaderRoute: typeof AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/dashboard/$slug/services/_pages/$serviceEstablishmentId': {
      id: '/dashboard/$slug/services/_pages/$serviceEstablishmentId'
      path: '/services/$serviceEstablishmentId'
      fullPath: '/dashboard/$slug/services/$serviceEstablishmentId'
      preLoaderRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/services/_pages/new/': {
      id: '/dashboard/$slug/services/_pages/new/'
      path: '/services/new'
      fullPath: '/dashboard/$slug/services/new/'
      preLoaderRoute: typeof DashboardSlugServicesPagesNewIndexRouteImport
      parentRoute: typeof DashboardSlugLayoutRoute
    }
    '/dashboard/$slug/services/_pages/$serviceEstablishmentId/info/': {
      id: '/dashboard/$slug/services/_pages/$serviceEstablishmentId/info/'
      path: '/info'
      fullPath: '/dashboard/$slug/services/$serviceEstablishmentId/info/'
      preLoaderRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRouteImport
      parentRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute
    }
    '/dashboard/$slug/services/_pages/$serviceEstablishmentId/edit/': {
      id: '/dashboard/$slug/services/_pages/$serviceEstablishmentId/edit/'
      path: '/edit'
      fullPath: '/dashboard/$slug/services/$serviceEstablishmentId/edit/'
      preLoaderRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRouteImport
      parentRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedEstablishmentIndexRoute: typeof AuthenticatedEstablishmentIndexRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute: typeof AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute
  AuthenticatedEstablishmentRoutesNewIndexRoute: typeof AuthenticatedEstablishmentRoutesNewIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedEstablishmentIndexRoute: AuthenticatedEstablishmentIndexRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute:
    AuthenticatedEstablishmentRoutesEstablishmentSlugIndexRoute,
  AuthenticatedEstablishmentRoutesNewIndexRoute:
    AuthenticatedEstablishmentRoutesNewIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteChildren {
  DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute
  DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute
}

const DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteChildren: DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteChildren =
  {
    DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute:
      DashboardSlugServicesPagesServiceEstablishmentIdEditIndexRoute,
    DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute:
      DashboardSlugServicesPagesServiceEstablishmentIdInfoIndexRoute,
  }

const DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteWithChildren =
  DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute._addFileChildren(
    DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteChildren,
  )

interface DashboardSlugLayoutRouteChildren {
  DashboardSlugBookingsIndexRoute: typeof DashboardSlugBookingsIndexRoute
  DashboardSlugCollaboratorsIndexRoute: typeof DashboardSlugCollaboratorsIndexRoute
  DashboardSlugCustomersIndexRoute: typeof DashboardSlugCustomersIndexRoute
  DashboardSlugOverviewIndexRoute: typeof DashboardSlugOverviewIndexRoute
  DashboardSlugReviewsIndexRoute: typeof DashboardSlugReviewsIndexRoute
  DashboardSlugServicesIndexRoute: typeof DashboardSlugServicesIndexRoute
  DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute: typeof DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteWithChildren
  DashboardSlugServicesPagesNewIndexRoute: typeof DashboardSlugServicesPagesNewIndexRoute
}

const DashboardSlugLayoutRouteChildren: DashboardSlugLayoutRouteChildren = {
  DashboardSlugBookingsIndexRoute: DashboardSlugBookingsIndexRoute,
  DashboardSlugCollaboratorsIndexRoute: DashboardSlugCollaboratorsIndexRoute,
  DashboardSlugCustomersIndexRoute: DashboardSlugCustomersIndexRoute,
  DashboardSlugOverviewIndexRoute: DashboardSlugOverviewIndexRoute,
  DashboardSlugReviewsIndexRoute: DashboardSlugReviewsIndexRoute,
  DashboardSlugServicesIndexRoute: DashboardSlugServicesIndexRoute,
  DashboardSlugServicesPagesServiceEstablishmentIdLayoutRoute:
    DashboardSlugServicesPagesServiceEstablishmentIdLayoutRouteWithChildren,
  DashboardSlugServicesPagesNewIndexRoute:
    DashboardSlugServicesPagesNewIndexRoute,
}

const DashboardSlugLayoutRouteWithChildren =
  DashboardSlugLayoutRoute._addFileChildren(DashboardSlugLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  ErrorRoute: ErrorRoute,
  DashboardSlugLayoutRoute: DashboardSlugLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
